//! Pure builders for the shell commands the engine runs over SSH. No I/O here,
//! so every command shape is unit-tested.

/// Named docker volume that holds the server identity + config (server.toml,
/// the sqlite user DB, QUIC cert/key). Persists across container recreation, so
/// `teardown --purge` must remove it explicitly to force a clean re-provision.
pub const DATA_VOLUME: &str = "leshiy-data";

/// Public IPv4 resolvers appended after any host-detected IPv4 resolver. Docker
/// tries `--dns` servers in order, so the host's own resolver (respecting
/// cloud-internal DNS that blocks external egress, e.g. Yandex/GCP) is used first
/// and these are the safety net. Both are IPv4 so they are reachable on the
/// IPv4-only default bridge — the exact reachability the v1.6.4 incident lacked
/// when an IPv6-only resolver was spliced in and every handshake black-holed.
pub const DNS_PUBLIC_FALLBACK: &[&str] = &["1.1.1.1", "8.8.8.8"];

/// Probe whether docker is on PATH. Prints `yes`/`no`.
pub fn detect_docker_cmd() -> &'static str {
    "command -v docker >/dev/null 2>&1 && echo yes || echo no"
}

/// Remove the persistent data volume (used by `teardown --purge`).
pub fn volume_rm_cmd() -> String {
    format!("sudo docker volume rm {DATA_VOLUME}")
}

/// Install Docker by sniffing the available package manager. The whole script
/// runs under a single `sudo` so password-sudo mode only needs one prompt
/// (the transport primes `sudo -S` once per command).
pub fn install_docker_cmd() -> &'static str {
    "sudo sh -c 'set -e; \
     if command -v apt-get >/dev/null 2>&1; then apt-get update && apt-get install -y docker.io; \
     elif command -v dnf >/dev/null 2>&1; then dnf install -y docker; \
     elif command -v yum >/dev/null 2>&1; then yum install -y docker; \
     elif command -v zypper >/dev/null 2>&1; then zypper install -y docker; \
     elif command -v pacman >/dev/null 2>&1; then pacman -Sy --noconfirm docker; \
     else echo no supported package manager >&2; exit 1; fi; \
     systemctl enable --now docker'"
}

pub fn pull_cmd(image_ref: &str) -> String {
    format!("sudo docker pull {image_ref}")
}

/// `docker run` for the leshiy server. REALITY is TCP on `listen_port`; QUIC (if
/// any) is UDP. Config is generated by the image's `boot` entrypoint from the
/// passed env vars and persisted on the `leshiy-data` volume.
pub fn run_cmd(
    container: &str,
    image_ref: &str,
    listen_port: u16,
    quic_port: Option<u16>,
    dns: &[&str],
    envs: &[(String, String)],
) -> String {
    // --user 0:0: the image's default `nonroot` user can't write the root-owned
    // `leshiy-data` volume, so `boot` fails to emit server.toml + the sqlite DB
    // and the --restart container crash-loops (later `docker exec` then races a
    // restarting container → "No such exec instance"). Root in-container matches
    // the install.sh docker path.
    let mut s = format!(
        "sudo docker run -d --name {container} --restart=unless-stopped \
         --user 0:0 --cap-add=NET_ADMIN -v {DATA_VOLUME}:/etc/leshiy -p {listen_port}:{listen_port}"
    );
    // --dns: the REALITY server must resolve `dest` from *inside* the container.
    // Docker's default resolver (8.8.8.8, or the host's 127.0.0.53 systemd stub)
    // is unreachable on many clouds (Yandex, GCP), so DNS silently black-holes and
    // every handshake stalls. The engine passes the host's real IPv4 upstream
    // first, then a public IPv4 fallback; Docker tries them in order. Multiple
    // `--dns` are emitted so an unreachable lead resolver falls through.
    for server in dns {
        s.push_str(&format!(" --dns {server}"));
    }
    if let Some(q) = quic_port {
        s.push_str(&format!(" -p {q}:{q}/udp"));
    }
    for (k, v) in envs {
        // values are operator-supplied host:port / sni; single-quote-escape for safety.
        let safe = v.replace('\'', "'\\''");
        s.push_str(&format!(" -e {k}='{safe}'"));
    }
    s.push_str(&format!(" {image_ref} boot"));
    s
}

pub fn ps_names_cmd() -> &'static str {
    "sudo docker ps --format '{{.Names}}'"
}

/// Print the host's first container-usable **IPv4** DNS server (or nothing).
///
/// Prefers a non-loopback `nameserver` from `/etc/resolv.conf`; on
/// systemd-resolved hosts that file points at the `127.0.0.53` stub (unreachable
/// from a container), so we also read `/run/systemd/resolve/resolv.conf`, which
/// carries the real upstreams. We positively match an IPv4 dotted-quad and drop
/// `127.*` loopback: an IPv6 resolver is unreachable on the IPv4-only default
/// bridge (`EnableIPv6=false`), so selecting one black-holes every in-container
/// lookup — the v1.6.4 outage. IPv6 and `::1` are excluded by the IPv4 match. No
/// sudo: both files are world-readable. Empty output → the engine uses the public
/// IPv4 fallback (see [`DNS_PUBLIC_FALLBACK`]).
pub fn detect_host_dns_cmd() -> &'static str {
    "grep -h '^nameserver' /etc/resolv.conf /run/systemd/resolve/resolv.conf 2>/dev/null \
     | awk '{print $2}' | grep -E '^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$' | grep -vE '^127\\.' | head -n1"
}

/// Whether a detected DNS server string is a bare IP literal safe to splice into
/// a `docker run` command. Rejects empty and anything with shell metacharacters.
pub fn valid_dns_addr(s: &str) -> bool {
    !s.is_empty()
        && s.len() <= 45 // longest possible IPv6 textual form
        && s.bytes()
            .all(|b| b.is_ascii_hexdigit() || matches!(b, b'.' | b':'))
}

/// Probe whether `ufw` is installed AND active. Prints `active` / `inactive`.
///
/// Docker publishes ports by inserting its own iptables rules, which usually
/// bypass ufw's INPUT chain — but not every host is configured that way, and an
/// active ufw is a common reason a freshly provisioned server is unreachable, so
/// we open the port explicitly when ufw is running. Wrapped in a single leading
/// `sudo sh -c` (like `install_docker_cmd`): `ufw status` needs root, and only a
/// LEADING `sudo` gets the password fed on stdin.
pub fn detect_ufw_active_cmd() -> &'static str {
    "sudo sh -c 'command -v ufw >/dev/null 2>&1 && \
     ufw status 2>/dev/null | grep -qi \"^Status: active\" && echo active || echo inactive'"
}

/// Open the REALITY/TCP listen port (and the QUIC/UDP port, if any) in ufw.
/// `ufw allow` is idempotent (a duplicate rule is skipped). Runs under one
/// leading `sudo sh -c` so a single stdin password prime covers both calls.
pub fn ufw_allow_cmd(listen_port: u16, quic_port: Option<u16>) -> String {
    let mut inner = format!("ufw allow {listen_port}/tcp");
    if let Some(q) = quic_port {
        inner.push_str(&format!(" && ufw allow {q}/udp"));
    }
    format!("sudo sh -c '{inner}'")
}

pub fn exec_user_add_cmd(container: &str, extra_args: &str) -> String {
    format!(
        "sudo docker exec {container} leshiy user add --config /etc/leshiy/server.toml {extra_args}"
    )
}

pub fn exec_user_list_json_cmd(container: &str) -> String {
    format!("sudo docker exec {container} leshiy user list --json --config /etc/leshiy/server.toml")
}

pub fn exec_user_rm_cmd(container: &str, short_id: &str) -> String {
    format!(
        "sudo docker exec {container} leshiy user rm {short_id} --config /etc/leshiy/server.toml"
    )
}

pub fn parse_ps_names(stdout: &str) -> Vec<String> {
    stdout
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .map(str::to_string)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pull_and_run_shape() {
        assert_eq!(
            pull_cmd("ghcr.io/x/leshiy:1.5.0"),
            "sudo docker pull ghcr.io/x/leshiy:1.5.0"
        );
    }

    #[test]
    fn run_cmd_has_boot_volume_env_and_ports() {
        let envs = vec![
            ("LESHIY_HOST".to_string(), "1.2.3.4:443".to_string()),
            (
                "LESHIY_DEST".to_string(),
                "www.microsoft.com:443".to_string(),
            ),
        ];
        let run = run_cmd("leshiy", "img:1", 443, Some(8443), &[], &envs);
        assert!(run.contains("--name leshiy"));
        assert!(run.contains("--restart=unless-stopped"));
        assert!(run.contains("--user 0:0"));
        assert!(run.contains("--cap-add=NET_ADMIN"));
        assert!(run.contains("-p 443:443"));
        assert!(run.contains("-p 8443:8443/udp"));
        assert!(run.contains("-v leshiy-data:/etc/leshiy"));
        assert!(run.contains("-e LESHIY_HOST='1.2.3.4:443'"));
        assert!(run.contains("-e LESHIY_DEST='www.microsoft.com:443'"));
        assert!(run.trim_end().ends_with("img:1 boot"));
    }

    #[test]
    fn run_cmd_without_quic_has_no_udp() {
        let run = run_cmd("leshiy", "img:1", 443, None, &[], &[]);
        assert!(!run.contains("/udp"));
        assert!(run.trim_end().ends_with("img:1 boot"));
    }

    #[test]
    fn parse_ps_extracts_names() {
        assert_eq!(parse_ps_names("leshiy\nother\n\n"), vec!["leshiy", "other"]);
        assert!(parse_ps_names("").is_empty());
    }

    #[test]
    fn detect_host_dns_cmd_reads_resolv_and_skips_loopback() {
        let c = detect_host_dns_cmd();
        // No sudo: resolv files are world-readable, and a leading sudo would need
        // a password prime it doesn't warrant.
        assert!(!c.starts_with("sudo"), "dns probe needs no sudo: {c}");
        assert!(c.contains("/etc/resolv.conf"));
        // systemd-resolved boxes point /etc/resolv.conf at 127.0.0.53 (unreachable
        // from a container); the real upstreams live here.
        assert!(c.contains("/run/systemd/resolve/resolv.conf"));
        // Must drop loopback nameservers — they're useless to the container.
        assert!(c.contains("127") && c.contains("nameserver"));
        // Must select an IPv4 dotted-quad only: an IPv6 resolver is unreachable on
        // the IPv4-only default bridge (the v1.6.4 incident), so the pipeline
        // positively matches `d.d.d.d` and never yields an IPv6 literal.
        assert!(
            c.contains(r"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"),
            "must positively match an IPv4 dotted-quad: {c}"
        );
        assert!(c.contains("head -n1"));
    }

    #[test]
    fn run_cmd_injects_multiple_dns_in_order() {
        // Docker tries `--dns` servers in order, so the host resolver must precede
        // the public fallback.
        let run = run_cmd("leshiy", "img:1", 443, None, &["10.130.0.2", "1.1.1.1"], &[]);
        let host_at = run.find("--dns 10.130.0.2").expect("host --dns present");
        let fb_at = run.find("--dns 1.1.1.1").expect("fallback --dns present");
        assert!(host_at < fb_at, "host resolver must come before fallback: {run}");
    }

    #[test]
    fn dns_public_fallback_are_ipv4_literals() {
        // The fallback must be usable on an IPv4-only bridge: valid, non-loopback,
        // and IPv4 (dotted, never a `:` IPv6 literal).
        assert!(!DNS_PUBLIC_FALLBACK.is_empty());
        for f in DNS_PUBLIC_FALLBACK {
            assert!(valid_dns_addr(f), "fallback must be a valid dns addr: {f}");
            assert!(f.contains('.') && !f.contains(':'), "fallback must be IPv4: {f}");
        }
    }

    #[test]
    fn valid_dns_addr_accepts_ips_rejects_injection() {
        assert!(valid_dns_addr("10.130.0.2"));
        assert!(valid_dns_addr("8.8.8.8"));
        assert!(valid_dns_addr("2a02:6b8::feed:0ff")); // IPv6
        assert!(!valid_dns_addr(""));
        assert!(!valid_dns_addr("10.0.0.1; reboot"));
        assert!(!valid_dns_addr("$(whoami)"));
        assert!(!valid_dns_addr("evil`id`"));
        assert!(!valid_dns_addr("a b"));
    }

    #[test]
    fn run_cmd_injects_dns_when_present() {
        let run = run_cmd("leshiy", "img:1", 443, None, &["10.130.0.2"], &[]);
        assert!(run.contains("--dns 10.130.0.2"), "run: {run}");
    }

    #[test]
    fn run_cmd_omits_dns_when_absent() {
        let run = run_cmd("leshiy", "img:1", 443, None, &[], &[]);
        assert!(!run.contains("--dns"));
    }

    #[test]
    fn detect_ufw_active_cmd_is_sudoized_and_probes_status() {
        let c = detect_ufw_active_cmd();
        // Must start with `sudo ` so the transport feeds the sudo password on
        // stdin (only a LEADING sudo is rewritten to `sudo -S`). `ufw status`
        // itself needs root.
        assert!(c.starts_with("sudo "), "must be sudoized: {c}");
        assert!(c.contains("command -v ufw"));
        assert!(c.contains("ufw status"));
        // Prints the sentinel the engine keys on.
        assert!(c.contains("echo active"));
        assert!(c.contains("echo inactive"));
    }

    #[test]
    fn ufw_allow_cmd_opens_tcp_and_udp_under_one_sudo() {
        let c = ufw_allow_cmd(443, Some(8443));
        // One leading sudo wrapping an `sh -c` so a single stdin password prime
        // covers every nested `ufw` call (matches install_docker_cmd's shape).
        assert!(c.starts_with("sudo sh -c "), "single-sudo wrapper: {c}");
        assert!(c.contains("ufw allow 443/tcp"));
        assert!(c.contains("ufw allow 8443/udp"));
    }

    #[test]
    fn ufw_allow_cmd_tcp_only_when_no_quic() {
        let c = ufw_allow_cmd(443, None);
        assert!(c.contains("ufw allow 443/tcp"));
        assert!(!c.contains("/udp"), "no udp rule without quic: {c}");
    }

    #[test]
    fn exec_user_add_targets_container() {
        let c = exec_user_add_cmd("leshiy", "--label self");
        assert_eq!(
            c,
            "sudo docker exec leshiy leshiy user add --config /etc/leshiy/server.toml --label self"
        );
    }

    #[test]
    fn user_list_json_and_rm_shapes() {
        assert_eq!(
            exec_user_list_json_cmd("leshiy"),
            "sudo docker exec leshiy leshiy user list --json --config /etc/leshiy/server.toml"
        );
        assert_eq!(
            exec_user_rm_cmd("leshiy", "0102030400000000"),
            "sudo docker exec leshiy leshiy user rm 0102030400000000 --config /etc/leshiy/server.toml"
        );
    }
}
