//! `leshiy service`: run the client as a systemd unit that survives logout.
//!
//! Two deliberate choices:
//!
//! * **The unit is `leshiy-client.service`, never `leshiy.service`.** The latter is the
//!   *server* unit — `lifecycle::uninstall` does `systemctl disable --now leshiy` and
//!   deletes `/etc/systemd/system/leshiy.service`, and `lifecycle::upgrade` restarts it. On
//!   a host running both, sharing the name would make `leshiy uninstall` delete the client
//!   service and `leshiy upgrade` restart the wrong process.
//! * **The `leshiy://` URI never appears in `ExecStart`.** It is a bearer credential, and
//!   argv is world-readable via `ps` and reprinted by `systemctl status`; a 0600 unit file
//!   would not help. It goes in a 0600 file passed as `--uri-file`.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

/// Marks units we generated. We refuse to overwrite anything lacking it, so a unit shipped
/// by `install.sh` or a distro package is never silently clobbered.
const MARKER: &str = "# Generated by `leshiy service start`. Edits will be overwritten.";

const UNIT: &str = "leshiy-client.service";

/// Where the unit and its credential live. The user scope needs no root and is the right
/// home for a SOCKS proxy; full-tunnel mode mutates routes, so it must be system scope.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Scope {
    User,
    System,
}

impl Scope {
    fn unit_path(self) -> Result<PathBuf> {
        Ok(match self {
            Scope::User => config_home()?.join("systemd/user").join(UNIT),
            Scope::System => PathBuf::from("/etc/systemd/system").join(UNIT),
        })
    }

    /// `ProtectHome=` in the system unit makes a home-directory credential unreadable, so
    /// the system scope keeps its URI under /etc.
    fn uri_path(self) -> Result<PathBuf> {
        Ok(match self {
            Scope::User => config_home()?.join("leshiy/client.uri"),
            Scope::System => PathBuf::from("/etc/leshiy/client.uri"),
        })
    }

    fn systemctl_args(self) -> &'static [&'static str] {
        match self {
            Scope::User => &["--user"],
            Scope::System => &[],
        }
    }
}

fn config_home() -> Result<PathBuf> {
    if let Some(x) = std::env::var_os("XDG_CONFIG_HOME") {
        return Ok(PathBuf::from(x));
    }
    let home = std::env::var_os("HOME").context("neither XDG_CONFIG_HOME nor HOME is set")?;
    Ok(PathBuf::from(home).join(".config"))
}

/// Write a bearer credential so it is never briefly world-readable.
///
/// `create_new` + `mode(0o600)` means the file is 0600 from the first byte; a
/// write-then-chmod would leave a window in which any local user could read the URI.
fn write_credential(path: &Path, uri: &str) -> Result<()> {
    use std::io::Write;
    use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
        std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o700))
            .with_context(|| format!("restrict {}", dir.display()))?;
    }
    let _ = std::fs::remove_file(path);
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)
        .with_context(|| format!("create {}", path.display()))?;
    f.write_all(uri.as_bytes())
        .and_then(|()| f.write_all(b"\n"))
        .with_context(|| format!("write {}", path.display()))
}

/// Read a URI written by [`write_credential`], refusing one any other local user can read.
pub fn read_credential(path: &Path) -> Result<String> {
    use std::os::unix::fs::PermissionsExt;
    let meta =
        std::fs::symlink_metadata(path).with_context(|| format!("read {}", path.display()))?;
    if meta.file_type().is_symlink() {
        anyhow::bail!("{} is a symlink; refusing to follow it", path.display());
    }
    let mode = meta.permissions().mode() & 0o777;
    if mode & 0o077 != 0 {
        anyhow::bail!(
            "{} is readable by others (mode {mode:o}); it holds a credential — chmod 600 it",
            path.display()
        );
    }
    Ok(std::fs::read_to_string(path)
        .with_context(|| format!("read {}", path.display()))?
        .trim()
        .to_string())
}

/// Exactly one of `--uri` / `--uri-file` must be given.
pub fn resolve_uri(uri: Option<&str>, uri_file: Option<&str>) -> Result<String> {
    match (uri, uri_file) {
        (Some(u), None) => Ok(u.to_string()),
        (None, Some(f)) => read_credential(Path::new(f)),
        (None, None) => anyhow::bail!("provide --uri or --uri-file"),
        (Some(_), Some(_)) => anyhow::bail!("--uri and --uri-file are mutually exclusive"),
    }
}

/// Fail early, and with the fix, when systemd cannot be driven here.
///
/// WSL2 is the common case: systemd is opt-in there, and without it `systemctl` fails with
/// "System has not been booted with systemd", which does not tell a user what to do.
fn preflight(scope: Scope) -> Result<()> {
    let booted = Path::new("/run/systemd/system").exists();
    if !booted {
        let wsl = std::fs::read_to_string("/proc/version")
            .is_ok_and(|v| v.to_lowercase().contains("microsoft"));
        if wsl {
            anyhow::bail!(
                "systemd is not running under WSL2. Enable it once:\n\
                 \n    printf '[boot]\\nsystemd=true\\n' | sudo tee -a /etc/wsl.conf\n\
                 \nthen from Windows run `wsl --shutdown` and reopen the shell."
            );
        }
        anyhow::bail!(
            "systemd is not running (no /run/systemd/system). `leshiy service` needs it; \
             run `leshiy connect` or `leshiy tun` in the foreground instead."
        );
    }
    if scope == Scope::User && std::env::var_os("XDG_RUNTIME_DIR").is_none() {
        anyhow::bail!(
            "XDG_RUNTIME_DIR is unset, so `systemctl --user` cannot reach the session bus. \
             This usually means a bare `su` or a non-login shell; log in properly, or use \
             --system."
        );
    }
    Ok(())
}

fn systemctl(scope: Scope, args: &[&str]) -> Result<std::process::Output> {
    let mut cmd = std::process::Command::new("systemctl");
    cmd.args(scope.systemctl_args()).args(args);
    cmd.output().context("run systemctl")
}

fn systemctl_ok(scope: Scope, args: &[&str]) -> Result<()> {
    let out = systemctl(scope, args)?;
    if !out.status.success() {
        anyhow::bail!(
            "systemctl {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

/// Keep a user service alive after logout.
///
/// Enabling linger is polkit-gated and silently fails over plain SSH or in containers, so
/// the result is verified rather than assumed — otherwise we would report success for a
/// service that dies at logout.
fn enable_linger() -> Result<()> {
    let user = std::env::var("USER").unwrap_or_default();
    let _ = std::process::Command::new("loginctl")
        .args(["enable-linger", &user])
        .output();
    let out = std::process::Command::new("loginctl")
        .args(["show-user", &user, "--property=Linger"])
        .output()
        .context("query linger state")?;
    if String::from_utf8_lossy(&out.stdout).trim() != "Linger=yes" {
        anyhow::bail!(
            "could not enable lingering for {user}, so the service would stop at logout. \
             Run: sudo loginctl enable-linger {user}"
        );
    }
    Ok(())
}

pub struct StartOpts<'a> {
    pub uri: &'a str,
    pub transport: &'a str,
    pub socks: Option<&'a str>,
    pub tun: bool,
    pub tun_name: &'a str,
    pub dns: &'a str,
    pub mtu: u16,
    pub ipv6: bool,
}

/// Full-tunnel mode mutates routes and DNS, so it can only run as a system unit.
pub fn scope_for(tun: bool) -> Scope {
    if tun { Scope::System } else { Scope::User }
}

/// Directories the full-tunnel unit must be able to write under `ProtectSystem=strict`.
///
/// `/etc` covers `resolv.conf` on an ordinary host. Where it is a symlink into another mount
/// the write follows the link and lands outside `/etc`, so that directory has to be listed
/// too — otherwise the engine dies with EROFS as soon as it applies the DNS override. WSL2
/// points it at `/mnt/wsl/resolv.conf`; systemd-resolved setups point it at `/run`.
fn read_write_paths() -> String {
    let mut paths = vec!["/etc".to_string()];
    if let Ok(target) = std::fs::canonicalize(RESOLV_CONF)
        && let Some(dir) = target.parent()
        && !dir.starts_with("/etc")
    {
        paths.push(dir.display().to_string());
    }
    paths.join(" ")
}

const RESOLV_CONF: &str = "/etc/resolv.conf";

/// True on WSL2, where the kernel is Microsoft's. A tunnel there covers WSL's own traffic
/// and leaves Windows applications untouched, which is worth saying out loud.
pub fn running_under_wsl() -> bool {
    std::fs::read_to_string("/proc/version").is_ok_and(|v| v.to_lowercase().contains("microsoft"))
}

fn render_unit(exe: &Path, uri_file: &Path, o: &StartOpts<'_>, scope: Scope) -> String {
    let mut exec = format!(
        "{} {} --uri-file {} --transport {}",
        exe.display(),
        if o.tun { "tun" } else { "client" },
        uri_file.display(),
        o.transport
    );
    if o.tun {
        exec.push_str(&format!(
            " --tun-name {} --dns {} --mtu {}",
            o.tun_name, o.dns, o.mtu
        ));
        if o.ipv6 {
            exec.push_str(" --ipv6");
        }
        if let Some(s) = o.socks {
            exec.push_str(&format!(" --socks {s}"));
        }
        // The unit already runs as root; without this the service would try to re-exec
        // through sudo, which has no terminal to prompt on and would hang start-up.
        exec.push_str(" --already-elevated");
    } else if let Some(s) = o.socks {
        exec.push_str(&format!(" --socks {s}"));
    }

    // `Restart=always` with the default start limit would park the unit in `failed` after a
    // boot where the network was not up yet — a lingering user service starts before it.
    // `After=network-online.target` is a no-op in a user unit, so the restart policy is the
    // only thing keeping it alive.
    let common = "\
Restart=always
RestartSec=5
Environment=RUST_LOG=leshiy=warn
";

    let hardening = if o.tun {
        // PrivateDevices=yes would hide /dev/net/tun, so it is deliberately absent.
        //
        // ProtectHome=yes makes /home appear empty, which means systemd cannot exec a
        // binary installed there at all -- it fails with 203/EXEC. install-client.sh puts
        // it in ~/.local/bin, so that is the normal case, not an edge one. Downgrade to
        // read-only only when the binary actually lives under a home directory; the
        // credential is in /etc, so a readable home does not expose it.
        // CAP_DAC_OVERRIDE is not optional here. Applying the DNS override means writing
        // the file /etc/resolv.conf resolves to, and under systemd-resolved that is
        // /run/systemd/resolve/stub-resolv.conf, owned by the systemd-resolve user at mode
        // 644. Being uid 0 is not enough to write it once the bounding set drops the
        // capability, so the engine fails with EACCES and the unit crash-loops.
        let rw_paths = read_write_paths();
        let protect_home = if exe.starts_with("/home") || exe.starts_with("/root") {
            "ProtectHome=read-only"
        } else {
            "ProtectHome=yes"
        };
        format!(
            "\
AmbientCapabilities=CAP_NET_ADMIN CAP_DAC_OVERRIDE
CapabilityBoundingSet=CAP_NET_ADMIN CAP_DAC_OVERRIDE
DeviceAllow=/dev/net/tun rw
ProtectSystem=strict
{protect_home}
ReadWritePaths={rw_paths}
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_NETLINK
TimeoutStopSec=30
"
        )
    } else {
        // A SOCKS proxy touches no devices or routes, so it can be locked down hard.
        "\
NoNewPrivileges=yes
CapabilityBoundingSet=
ProtectSystem=strict
ProtectHome=read-only
PrivateDevices=yes
PrivateTmp=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictSUIDSGID=yes
RestrictRealtime=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
UMask=0077
"
        .to_string()
    };

    let (after, wanted_by) = match scope {
        Scope::System => (
            "After=network-online.target\nWants=network-online.target\n",
            "multi-user.target",
        ),
        Scope::User => ("", "default.target"),
    };

    format!(
        "{MARKER}\n[Unit]\nDescription=Leshiy client tunnel\n{after}\
StartLimitIntervalSec=0\n\n[Service]\n\
         Type=notify\nNotifyAccess=main\nTimeoutStartSec=60\nExecStart={exec}\n{common}{hardening}\n\
         [Install]\nWantedBy={wanted_by}\n"
    )
}

pub fn start(o: &StartOpts<'_>) -> Result<()> {
    let scope = scope_for(o.tun);
    preflight(scope)?;

    let exe = crate::lifecycle::self_path()?;
    let unit_path = scope.unit_path()?;
    let uri_path = scope.uri_path()?;

    if unit_path.exists() {
        let existing = std::fs::read_to_string(&unit_path).unwrap_or_default();
        if !existing.contains(MARKER) {
            anyhow::bail!(
                "{} exists and was not generated by leshiy; refusing to overwrite it",
                unit_path.display()
            );
        }
    }

    // Retire any unit in the other scope first: two same-named units would then disagree,
    // and `status`/`stop` could act on the idle one while the other kept the machine
    // tunneled. One installed unit at a time is the invariant.
    let other = if scope == Scope::System {
        Scope::User
    } else {
        Scope::System
    };
    if other.unit_path()?.exists() {
        let _ = systemctl(other, &["disable", "--now", UNIT]);
        let _ = std::fs::remove_file(other.unit_path()?);
        let _ = systemctl(other, &["daemon-reload"]);
        crate::ui::hint(&format!("removed the previous {other:?}-scope unit"));
    }

    write_credential(&uri_path, o.uri)?;
    let unit = render_unit(&exe, &uri_path, o, scope);
    if let Some(dir) = unit_path.parent() {
        std::fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
    }
    std::fs::write(&unit_path, unit).with_context(|| format!("write {}", unit_path.display()))?;

    systemctl_ok(scope, &["daemon-reload"])?;
    if scope == Scope::User {
        enable_linger()?;
    }
    // `enable --now` so it also comes back after a reboot; linger alone only survives
    // logout. `Type=notify` makes this block until the tunnel is actually connected.
    systemctl_ok(scope, &["enable", "--now", UNIT])?;

    crate::ui::ok(&format!("{UNIT} started and connected"));
    let sc = if scope == Scope::User { "--user " } else { "" };
    crate::ui::hint(&format!(
        "status:  leshiy service status\n  logs:    leshiy service logs -f\n  stop:    leshiy service stop\n  (raw:    systemctl {sc}status {UNIT})"
    ));
    Ok(())
}

/// Look in whichever scope actually has a unit installed, so `stop`/`status`/`logs` need no
/// flag to mirror whatever `start` chose.
/// Every scope that currently has a unit installed.
///
/// Both can exist at once — proxy mode writes a user unit and `--tun` a system one, under
/// the same name. Picking the first that merely *exists* is what made `status` report an
/// idle user unit while the system tunnel was running, and made `stop` claim success after
/// stopping the wrong one, leaving the machine tunneled with no obvious way back.
fn installed_scopes() -> Result<Vec<Scope>> {
    let mut found = Vec::new();
    for scope in [Scope::System, Scope::User] {
        if scope.unit_path()?.exists() {
            found.push(scope);
        }
    }
    if found.is_empty() {
        anyhow::bail!("no {UNIT} installed; run `leshiy service start` first");
    }
    Ok(found)
}

fn is_active(scope: Scope) -> bool {
    systemctl(scope, &["is-active", "--quiet", UNIT]).is_ok_and(|o| o.status.success())
}

/// Choose which installed unit a read command should describe: the running one wins.
///
/// Split out from the I/O so the selection itself is testable — reporting on an idle unit
/// while another is live is the whole bug this guards against.
fn pick_scope(installed: &[Scope], active: impl Fn(Scope) -> bool) -> Option<Scope> {
    installed
        .iter()
        .copied()
        .find(|s| active(*s))
        .or_else(|| installed.first().copied())
}

/// The scope to report on: whichever is actually running, else the only one installed.
fn managing_scope() -> Result<Scope> {
    let scopes = installed_scopes()?;
    pick_scope(&scopes, is_active).ok_or_else(|| anyhow::anyhow!("no {UNIT} installed"))
}

/// Whether stopping needs root — true when *any* installed unit is system-scoped, since
/// `stop` tears down every scope rather than guessing which one the user meant.
pub fn stop_needs_root() -> Result<bool> {
    Ok(installed_scopes()?.contains(&Scope::System))
}

pub fn stop() -> Result<()> {
    // Tear down every installed scope, not just one. A user unit and a system unit can both
    // exist, and stopping only the one we guessed at is how a tunnel survived "stop".
    for scope in installed_scopes()? {
        systemctl_ok(scope, &["disable", "--now", UNIT])?;
        crate::ui::ok(&format!("{UNIT} stopped ({scope:?} scope)"));
    }
    Ok(())
}

pub fn status() -> Result<()> {
    let scope = managing_scope()?;
    let out = systemctl(scope, &["status", "--no-pager", UNIT])?;
    print!("{}", String::from_utf8_lossy(&out.stdout));
    Ok(())
}

pub fn logs(follow: bool) -> Result<()> {
    let scope = managing_scope()?;
    let mut cmd = std::process::Command::new("journalctl");
    if scope == Scope::User {
        cmd.arg("--user");
    }
    cmd.args(["-u", UNIT, "-n", "50"]);
    if follow {
        cmd.arg("-f");
    }
    cmd.status().context("run journalctl")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn opts<'a>(tun: bool, socks: Option<&'a str>) -> StartOpts<'a> {
        StartOpts {
            uri: "leshiy://k@example.com:443?sni=a&sid=b",
            transport: "auto",
            socks,
            tun,
            tun_name: "leshiy0",
            dns: "1.1.1.1",
            mtu: 1400,
            ipv6: false,
        }
    }

    /// The whole point of `--uri-file`: the credential must not reach argv, where `ps` and
    /// `systemctl status` expose it to every local user.
    #[test]
    fn unit_never_embeds_the_uri() {
        for tun in [false, true] {
            let o = opts(tun, None);
            let unit = render_unit(
                Path::new("/usr/local/bin/leshiy"),
                Path::new("/etc/leshiy/client.uri"),
                &o,
                scope_for(tun),
            );
            assert!(
                !unit.contains("leshiy://"),
                "credential leaked into unit:\n{unit}"
            );
            assert!(unit.contains("--uri-file /etc/leshiy/client.uri"), "{unit}");
        }
    }

    /// Proxy mode installs a user unit and `--tun` a system one, under the same name, so
    /// both can be on disk. Choosing by mere existence reported the idle user unit while
    /// the system tunnel was live — and `stop` then "succeeded" against the wrong unit,
    /// leaving the machine tunneled with no working way back.
    #[test]
    fn a_running_unit_wins_over_a_merely_installed_one() {
        let both = [Scope::System, Scope::User];
        assert_eq!(
            pick_scope(&both, |s| s == Scope::System),
            Some(Scope::System)
        );
        assert_eq!(pick_scope(&both, |s| s == Scope::User), Some(Scope::User));
        // Neither running: fall back deterministically rather than at random.
        assert_eq!(pick_scope(&both, |_| false), Some(Scope::System));
        assert_eq!(pick_scope(&[], |_| true), None);
        assert_eq!(
            pick_scope(&[Scope::User], |_| false),
            Some(Scope::User),
            "a lone unit is reported even when stopped"
        );
    }

    #[test]
    fn proxy_is_a_user_unit_and_vpn_is_a_system_unit() {
        assert_eq!(scope_for(false), Scope::User);
        assert_eq!(scope_for(true), Scope::System);
    }

    /// A root-run unit must not try to re-exec through sudo: there is no terminal to
    /// prompt on, so start-up would hang until TimeoutStartSec.
    #[test]
    fn vpn_unit_suppresses_the_sudo_reexec() {
        let o = opts(true, None);
        let unit = render_unit(
            Path::new("/x/leshiy"),
            Path::new("/etc/leshiy/client.uri"),
            &o,
            Scope::System,
        );
        assert!(unit.contains("--already-elevated"), "{unit}");
    }

    /// Being root is not sufficient to write the DNS file: under systemd-resolved it is
    /// owned by the systemd-resolve user, so dropping CAP_DAC_OVERRIDE from the bounding
    /// set makes the engine fail with EACCES and crash-loop the unit.
    #[test]
    fn vpn_unit_keeps_the_capability_needed_to_rewrite_dns() {
        let unit = render_unit(
            Path::new("/usr/local/bin/leshiy"),
            Path::new("/etc/leshiy/client.uri"),
            &opts(true, None),
            Scope::System,
        );
        for line in ["AmbientCapabilities=", "CapabilityBoundingSet="] {
            let got = unit
                .lines()
                .find(|l| l.starts_with(line))
                .unwrap_or_else(|| panic!("{line} missing:\n{unit}"));
            assert!(got.contains("CAP_NET_ADMIN"), "{got}");
            assert!(got.contains("CAP_DAC_OVERRIDE"), "{got}");
        }
    }

    /// Under ProtectSystem=strict the engine can only write what ReadWritePaths lists. When
    /// resolv.conf is a symlink into another mount — /mnt/wsl on WSL2, /run under
    /// systemd-resolved — listing /etc alone is not enough and applying the DNS override
    /// fails with EROFS, crash-looping the unit.
    #[test]
    fn read_write_paths_cover_wherever_resolv_conf_really_lives() {
        let paths = read_write_paths();
        assert!(paths.contains("/etc"), "{paths}");
        if let Ok(target) = std::fs::canonicalize("/etc/resolv.conf")
            && let Some(dir) = target.parent()
            && !dir.starts_with("/etc")
        {
            assert!(
                paths.contains(&dir.display().to_string()),
                "resolv.conf resolves to {} but ReadWritePaths is {paths}",
                target.display()
            );
        }
    }

    /// ProtectHome=yes makes /home appear empty to the service, so systemd cannot exec a
    /// binary there and the unit dies with 203/EXEC. install-client.sh installs to
    /// ~/.local/bin, so this is the default layout, not a corner case.
    #[test]
    fn vpn_unit_can_exec_a_binary_installed_under_home() {
        let o = opts(true, None);
        let home = render_unit(
            Path::new("/home/someone/.local/bin/leshiy"),
            Path::new("/etc/leshiy/client.uri"),
            &o,
            Scope::System,
        );
        assert!(home.contains("ProtectHome=read-only"), "{home}");
        assert!(!home.contains("ProtectHome=yes"), "{home}");

        // A system-wide install needs no such concession, so keep the stronger setting.
        let sys = render_unit(
            Path::new("/usr/local/bin/leshiy"),
            Path::new("/etc/leshiy/client.uri"),
            &o,
            Scope::System,
        );
        assert!(sys.contains("ProtectHome=yes"), "{sys}");
    }

    /// PrivateDevices=yes hides /dev/net/tun; the failure looks like a permissions bug.
    #[test]
    fn vpn_unit_does_not_hide_the_tun_device() {
        let o = opts(true, None);
        let unit = render_unit(
            Path::new("/x/leshiy"),
            Path::new("/etc/leshiy/client.uri"),
            &o,
            Scope::System,
        );
        assert!(!unit.contains("PrivateDevices=yes"), "{unit}");
        assert!(unit.contains("DeviceAllow=/dev/net/tun rw"), "{unit}");
    }

    /// A lingering user service starts before the network is up; with the default start
    /// limit it would exhaust its retries and park in `failed` permanently.
    #[test]
    fn user_unit_cannot_exhaust_its_start_limit() {
        let unit = render_unit(
            Path::new("/x/leshiy"),
            Path::new("/c/client.uri"),
            &opts(false, None),
            Scope::User,
        );
        assert!(unit.contains("Restart=always"), "{unit}");

        // systemd only parses StartLimitIntervalSec in [Unit]. Under [Service] it logs
        // "Unknown key name ... ignoring" and the protection above is silently inert.
        let unit_section = unit
            .split("[Service]")
            .next()
            .expect("unit must have a [Unit] section");
        assert!(
            unit_section.contains("StartLimitIntervalSec=0"),
            "StartLimitIntervalSec must live in [Unit], got:\n{unit}"
        );
    }

    #[test]
    fn unit_is_notify_type_so_start_blocks_until_connected() {
        let unit = render_unit(
            Path::new("/x/leshiy"),
            Path::new("/c/client.uri"),
            &opts(false, None),
            Scope::User,
        );
        assert!(unit.contains("Type=notify"), "{unit}");
    }

    #[test]
    fn combined_mode_passes_socks_through() {
        let unit = render_unit(
            Path::new("/x/leshiy"),
            Path::new("/etc/leshiy/client.uri"),
            &opts(true, Some("127.0.0.1:1080")),
            Scope::System,
        );
        assert!(unit.contains("--socks 127.0.0.1:1080"), "{unit}");
    }

    #[test]
    fn credential_is_written_0600_and_round_trips() {
        use std::os::unix::fs::PermissionsExt;
        let dir = std::env::temp_dir().join(format!("leshiy-cred-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("client.uri");
        write_credential(&p, "leshiy://secret@h:443").unwrap();

        let mode = std::fs::metadata(&p).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "credential must not be readable by others");
        assert_eq!(read_credential(&p).unwrap(), "leshiy://secret@h:443");

        std::fs::set_permissions(&p, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert!(
            read_credential(&p).is_err(),
            "must refuse a world-readable credential"
        );

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn resolve_uri_requires_exactly_one_source() {
        assert_eq!(resolve_uri(Some("leshiy://x"), None).unwrap(), "leshiy://x");
        assert!(resolve_uri(None, None).is_err());
        assert!(resolve_uri(Some("a"), Some("b")).is_err());
    }
}
